SELECT COUNT(*)
FROM MAP_PRINCIPAL_REPO
WHERE BITAND(PERMISSION_BITS, 382) > 0;

SELECT DISTINCT PERMISSION
FROM MAP_PRINCIPAL_REPO
WHERE BITAND(PERMISSION_BITS, 382) > 0;

SELECT COUNT(*)
FROM MAP_PRINCIPAL_REPO
WHERE PERMISSION LIKE '%WRITE%' OR PERMISSION LIKE '%ADMIN%' OR PERMISSION LIKE '%CREATE_BRANCH%' OR PERMISSION LIKE '%DELETE_BRANCH%' OR
      PERMISSION LIKE '%CREATE_REPO%' OR PERMISSION LIKE '%DELETE_REPO%' OR PERMISSION LIKE '%CREATE_TAG%';

SELECT DISTINCT PERMISSION
FROM MAP_PRINCIPAL_REPO
WHERE PERMISSION LIKE '%WRITE%' OR PERMISSION LIKE '%ADMIN%' OR PERMISSION LIKE '%CREATE_BRANCH%' OR PERMISSION LIKE '%DELETE_BRANCH%' OR
      PERMISSION LIKE '%CREATE_REPO%' OR PERMISSION LIKE '%DELETE_REPO%' OR PERMISSION LIKE '%CREATE_TAG%';
